### ISSUE TITLE
the format of cuts

### ISSUE THREAD

**Issue by ccding** [scalog/scalog-old#3]
Currently we use vectors to represent cuts. I think it would be better to use maps, because after adding and finalizing shards, the cut of live shards may become very sparse.

**Comment by davidchuyaya** [comment]
Could you clarify what you mean? Currently cuts are represented (at least on the ordering layer) as:
- **CommittedCuts**: `Map<ShardID, Map<ReplicaID, Cut>>`. ReplicaID is from 0 to n per shard, where n = number of replicas per shard, so `Map<ReplicaID, Cut>` is simplified to `List<Cut>`.
- **ContestedCuts**: `Map<ShardID, Map<ReplicaID, Map<ReplicaID, Cut>>>`. This structure holds what cut each replica believes each other replica has. So for each shard, each replica has a list of cuts for every replica. Again, `Map<ReplicaID, Cut>` is simplified to `List<Cut>` since we know the indexing is not sparse.

**Comment by ccding** [comment]
https://github.com/scalog/scalog/blob/master/order/messaging/order.proto#L28

ReplicaID  is not always from 0 to n. In a long run, if shards are frequently created and finalized, ReplicaID of live shards may be something like 0,1, 10,11, 84,85, 100,101, 500,501 in a 5-shard case. It makes no sense to send a vector of size 500 over the network

**Comment by davidchuyaya** [comment]
I think you're confusing ReplicaID and ShardID.

ReplicaID is the id of individual servers **within a shard**. Assuming that a shard will always have the same number of servers (if it isn't finalized), they will be ordered 0 to n per shard.

ShardID is the id of shards, which can be sparse as you said, which is why they're stored in maps with integer keys.

**Comment by davidchuyaya** [comment]
I think you believe ReplicaIDs cannot overlap between servers of different shards. I'll confirm if they can with @evantzhao. Here's where the ReplicaID is retrieved for each data layer server. So long as the parameter is ordered as expected, we should be fine.
https://github.com/scalog/scalog/blob/master/data/main.go#L170

**Comment by ccding** [comment]
I understand this is not an issue for tentative cuts. But for committed cuts, it seems not the same case. Let's say ShardIDs may be sparse.

**Comment by ccding** [comment]
> ShardID is the id of shards, which can be sparse as you said, which is why they're stored in maps with integer keys.

Are they stored in maps but sent in vector over the network? see the link I posted above

**Comment by ccding** [comment]
I checked the code again and see what you did.

I'd like to offload as much workload as possible from the ordering layer to the data layer. Say, the ordering layer send the committed cut (map) to all storage servers, and each storage server individually compute whatever it needs.

We will be able to build layered aggregators later, to further reduce workload from the ordering layer.

**Comment by ccding** [comment]
I checked the code again and see what you did.

Currently ordering layer sends different messages for each shard, then the ReportResponse message includes a fraction of committed cut (for that specific shard). Then it could be represented as a vector.

I'd like to offload as much workload as possible from the ordering layer to the data layer. Say, the ordering layer sends the committed cut (map) to all storage servers, and each storage server individually computes whatever it needs.

This also makes us be able to build layered aggregators later, to further reduce workload from the ordering layer.

**Comment by evantzhao** [comment]
Gotcha -- we'll move the cut computation to the data layer. But yeah, what David mentioned about the shardID and replicaID should be true -- shardID is the unique identifier (that does not have to be contiguous) and replicaID will always be from 0 -> numReplicasPerShard in each shard

**Comment by ccding** [comment]
> replicaID will always be from 0 -> numReplicasPerShard in each shard

This is okay
